language: node_js
node_js:
  - "node"
script:
  - yarn run lint
  - yarn run build
  - mv CNAME ./dist/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: sources