# This workflow builds the site and pushes the build to the gh-pages branch. From there, the GitHub Pages deployment action takes it live.
name: Build Vue
on: 
  workflow_dispatch:
  # Triggers the workflow on release events, but not draft ones
  release:
    types: [published]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'sdonchez'
        reponame: 'sdonchez.github.io'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
